#!/usr/bin/env python3
"""
Offline analyzer for PCAP files captured by sniffer.py
"""

import argparse
import sys
from collections import Counter

try:
    from scapy.all import rdpcap, IP, TCP, UDP, ICMP, DNS, DNSQR, ARP
except ImportError:
    print("[!] Scapy is not installed. Run: pip install scapy")
    sys.exit(1)


def analyze_packets(packets):
    proto_counts = Counter()
    src_ips = Counter()
    dst_ips = Counter()
    ports = Counter()
    dns_queries = Counter()

    for pkt in packets:
        if ARP in pkt:
            proto_counts["ARP"] += 1
            continue

        if IP in pkt:
            src_ips[pkt[IP].src] += 1
            dst_ips[pkt[IP].dst] += 1

            if DNS in pkt and DNSQR in pkt:
                proto_counts["DNS"] += 1
                domain = pkt[DNSQR].qname.decode(errors="replace").rstrip(".")
                dns_queries[domain] += 1
            elif TCP in pkt:
                proto_counts["TCP"] += 1
                ports[pkt[TCP].sport] += 1
                ports[pkt[TCP].dport] += 1
            elif UDP in pkt:
                proto_counts["UDP"] += 1
                ports[pkt[UDP].sport] += 1
                ports[pkt[UDP].dport] += 1
            elif ICMP in pkt:
                proto_counts["ICMP"] += 1
            else:
                proto_counts["OTHER"] += 1
        else:
            proto_counts["NON-IP"] += 1

    print("\n" + "=" * 60)
    print("Offline PCAP Analysis Report")
    print("=" * 60)
    print(f"Total packets: {len(packets)}\n")

    print("Protocol Distribution:")
    for proto, count in proto_counts.most_common():
        print(f"- {proto}: {count}")

    print("\nTop 5 Source IPs:")
    for ip, count in src_ips.most_common(5):
        print(f"- {ip}: {count}")

    print("\nTop 5 Destination IPs:")
    for ip, count in dst_ips.most_common(5):
        print(f"- {ip}: {count}")

    if ports:
        print("\nTop 10 Ports:")
        for port, count in ports.most_common(10):
            print(f"- Port {port}: {count}")

    if dns_queries:
        print("\nDNS Queries:")
        for domain, count in dns_queries.most_common(10):
            print(f"- {domain}: {count}")

    print("\nAnalysis complete.")


def main():
    parser = argparse.ArgumentParser(description="Analyze a PCAP file generated by the sniffer")
    parser.add_argument("pcap_file", help="Path to the PCAP file")
    args = parser.parse_args()

    packets = rdpcap(args.pcap_file)
    analyze_packets(packets)


if __name__ == "__main__":
    main()
    
